### PR TITLE
New: Reference with Timezone API

### PR DESCRIPTION
**Pull request by wanasit**
Calling for review: @benaubin @lostfictions @gobaldia @ptz0n @IanMitchell @ScottChapman @meister03 

This new API is aiming to fix the timezone issue raised in #364, #375, #385. The current `refDate` is a JavaScript Date object which doesn't contain timezone information. Thus, Chrono cannot really account for the timezone difference between the input text and the system.

For example:
```
chrono.parseDate("At 4pm tomorrow", new Date("Mon Jun 07 2021 04:00:00 GMT+0900 (JST)"))
// Output -> Tue Jun 08 2021 16:00:00 GMT+0900 (JST)

chrono.parseDate("At 4pm tomorrow", new Date("Sun Jun 06 2021 20:00:00 GMT+0100 (BST)"))
// Should actually be -> Mon Jun 07 2021 16:00:00 GMT+0100 (BST)
// but output -> Mon Jun 07 2021 08:00:00 GMT+0100 (BST)
```

Both of the output are `Tues Jun 08 2021 04:00:00 GMT+0900 (JST)` (= `Mon Jun 07 2021 08:00:00 GMT+0100 (BST)`), the later should be `Mon Jun 07 2021 16:00:00 GMT+0100 (BST)`.

---

In addition to reference date/time "instant" (which is what Date object actually represent), the new API will allow users to input the reference timezone:

```typescript
export interface ParsingReference {

    instant?: Date;

    timezone?: string | number;
}
```

This should be equivalent to [ZonedDateTime](https://tc39.es/proposal-temporal/docs/#Temporal-ZonedDateTime) in the new [Temporal proposal](https://tc39.es/proposal-temporal/). 

This API change will allow the callers to specify the reference timezone for the library to reference as default.

```typescript
chrono.parseDate("At 4pm tomorrow", {
  instant: new Date("Mon Jun 07 2021 04:00:00 GMT+0900 (JST)")
  timezone: "JST"
)
// Output -> Tue Jun 08 2021 16:00:00 GMT+0900 (JST)

chrono.parseDate("At 4pm tomorrow", {
  instant: new Date("Sun Jun 06 2021 20:00:00 GMT+0100 (BST)")
  timezone: "BST"
)
// Output-> Mon Jun 07 2021 16:00:00 GMT+0100 (BST)
```

while the timezone that is explicitly or implied from the text won't be effected.
```typescript
chrono.parseDate("2021-06-06T20:05:00+0100", {
  instant: new Date("Sun Jun 06 2021 20:00:00 GMT+0100 (BST)")
  timezone: "BST"
)
// Output-> Sun Jun 06 2021 20:05:00 GMT+0100 (BST)

chrono.parseDate("In 5 min", {
  instant: new Date("Sun Jun 06 2021 20:00:00 GMT+0100 (BST)")
  timezone: "BST"
)
// Output-> Sun Jun 06 2021 20:05:00 GMT+0100 (BST)
```

### CODE REVIEW

**Comment by IanMitchell** [comment]
Oooh I love this - I'm pretty sure this is perfect!

**Comment by meister03** [comment]
Yeah, amazing, this will make life so easy.
Are the timezones GMT, BST....?
and are there any  parsers, which can transform Timezones, like `America/New_York`  in  the upper format (`BST`/`GMT` ....) ?

**Comment by wanasit** [comment]
> Are the timezones GMT, BST....? and are there any parsers, which can transform Timezones, like America/New_York in the upper format (BST/GMT ....) ?

I'm thinking about support manual offset and basic timezone name look-up. So.. yes. GMT, BST, etc.
I think we should support tweaking the timezone dictionary, but full-parser or location to timezone detection would be too much.

**Comment by wanasit** [comment]
Thank you for your feedback. Let me roll this feature in a minor ver 2.3.x.

**Pull request merged**
