### PR TITLE
Added parsing for quarter

### PR DESCRIPTION
**Pull request by PriyankaSand**
This supports text like, "next quarter", "last quarter", "next two quarter", "after this quarter".

### CODE REVIEW

**Comment by PriyankaSand** [comment]
Hey @wanasit , can you please review this change and merge it.

**Comment by wanasit** [comment]
Sorry for the delay. Thanks for the improvement.

**Comment by PriyankaSand** [comment]
@wanasit , can you please release this change.

**Comment by wanasit** [comment]
Sorry for the delay.

**Comment by liamcain** [comment]
Just wanted to say thanks for this PR!! It's been on my todo list a while so I was happy to see someone else get to it

**Pull request merged**
