### PR TITLE
Add .npmignore file

### LINKED ISSUE #176: security vulnerabilities in dependencies
Retire (dependency vulnerability checker https://www.npmjs.com/package/retire) reports two vulnerabilities in Chrono's own dependencies.

(path)\node_modules\chrono-node\chrono.js
 ↳ moment.js 2.10.3 has known vulnerabilities: severity: low; summary: reDOS - regular expression denial of service; https://github.com/moment/moment/issues/2936
(path)\node_modules\chrono-node\test\qunit\jquery-1.7.1.min.js
 ↳ jquery 1.7.1.min has known vulnerabilities: severity: medium; bug: 11290, summary: Selector interpreted as HTML; http://bugs.jquery.com/ticket/11290 http://research.insecurelabs.org/jquery/test/ severity: medium; issue: 2432, summary: 3rd party CORS request may execute; https://github.com/jquery/jquery/issues/2432 http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/

Would simply bumping up the required version of moment resolve the first one?

Why is there an old jquery file included with chrono-node?

### PR DESCRIPTION
**Pull request by Seikho**
Resolves #176 by not publishing test files, config files and pre-built files to NPM.

### CODE REVIEW

**Comment by Schultzer** [comment]
This could be done in the package.json file too.
`"files": [
  chrono.js,
  chrono.min.js,
  timezone.js,
...
  ]`

**Comment by Seikho** [comment]
Happy to switch it over. I usually prefer to leave other people's `package.json` files alone :)

**Comment by Schultzer** [comment]
@Seikho You are right it's up to @wanasit  😀
Thank you for the contribution

**Comment by wanasit** [comment]
Thanks @Seikho! I agree with @Schultzer add files list into `package.json`.
We only need `chrono.js` and `chrono.min.js`.

**Pull request closed without merging**
