### PR TITLE
Change Guild to Guide

### LINKED ISSUE #79: Should the Guild be Guide?
I noticed you called the contribution section **Development Guild** is this a spelling mistake for **Guide**? If so I can put together a quick PR for you.

### PR DESCRIPTION
**Pull request by chadfawcett**
Resolves #79

### CODE REVIEW

**Comment by wanasit** [comment]
Ops! Thanks!

**Comment by penne12** [comment]
@wanasit Did you close this intentionally? [The mistake] is still there.

[dev-guild]: https://github.com/wanasit/chrono#development-guild

**Comment by wanasit** [comment]
I remember he sent me a PR and I've merged it already. haven’t I?

**Comment by penne12** [comment]
@wanasit I think you closed it instead.

**Comment by wanasit** [comment]
oh sorry. will make sure it merged this time.

**Pull request merged**
