### PR TITLE
Adding future relative dates: from now, out, forward

### PR DESCRIPTION
**Pull request by jonshaffer**
Love this parser :)

I needed functionality for future relative dates, so I used `ENTimeAgoFormatParser` as a base

Unit tests added

### CODE REVIEW

**Comment by benaubin** [comment]
Looks awesome so far. Just need tests 😄

**Comment by benaubin** [comment]
Looks good to me, just needs tests.

**Comment by jonshaffer** [comment]
I had an issue running this repo with node v7.x.x, it looks like there are graceful-fs dependencies down the chain that are preventing tests from running in that new version. As a result, I added the engines tag to package.json until that issue is fixed.

To fix:
- Update to a later release of Karma
- Update to a later release of Browserify

**Comment by wanasit** [comment]
@ jonshaffer I already update the Browserify and Karma in master.
Could you rebase or merge with the current master and add some test?

**Comment by alexgorbatchev** [comment]
Great job, would love to see this merged!

**Comment by wanasit** [comment]
Merged. Sorry that I didn't have time to look into this.

**Pull request merged**
