### PR TITLE
[DE] Add month names; translate time units

### PR DESCRIPTION
**Pull request by georgd**

### CODE REVIEW

**Comment by wanasit** [comment]
Hello, thanks for your contribution! Could you please take an extra 5-10min adding a few test cases with those words?

**Comment by georgd** [comment]
Ok, I’ll do so. Tests are an hour off here, 82 tests fail. Could you tell me how to calibrate it?

**Comment by wanasit** [comment]
You mean the test fails on the master branch on your local out-of-box? hmm. that's unexpected. Could you give me an example of the test that fails?

**Comment by georgd** [comment]
Yes, on the master branch. It looks like any test fails that involves calculating the hour. I’m on a Mac. Please let me know which information you need from me.

```
Test Suites: 34 failed, 31 passed, 65 total
Tests:       50 failed, 213 passed, 263 total
Snapshots:   0 total
Time:        12.579 s, estimated 29 s
```

This is the output of one test:

```
ts-jest[config] (WARN) Got `sourceMap: false` from tsconfig file "/Users/gduffner/Documents/dev/chrono/tsconfig.json". This will disable source map support in ts-jest 27. Please set `sourceMap: true` in your tsconfig file "/Users/gduffner/Documents/dev/chrono/tsconfig.json" if you want to keep source map support on
 FAIL  test/en/en.test.ts
  ✕ Test - Date + Time Expression (62 ms)
  ✓ Test - Time Expression (109 ms)
  ✕ Test - Quoted Expressions (4 ms)
  ✓ Test - Strict Mode (10 ms)
  ✕ Test - Random text (38 ms)
  ✓ Test - Wikipedia Texts (1 ms)
  ✓ Test - Parse multiple date results (1 ms)
  ✓ Test - Customize by removing time extraction (1 ms)

  ● Test - Date + Time Expression

    Expected date to be: Fri Apr 18 2014 13:00:00 GMT+0200 (Mitteleuropäische Sommerzeit) Received: Fri Apr 18 2014 14:00:00 GMT+0200 (Mitteleuropäische Sommerzeit) ([ParsingComponents {knownValues: {"year":2014,"month":4,"day":18,"hour":13,"minute":0,"meridiem":1}, impliedValues: {"second":0,"millisecond":0}}])

       7 |         expect(result.text).toBe("2014-04-18 13:00 - 16:00");
       8 |
    >  9 |         expect(result.start).toBeDate(new Date(2014, 4 - 1, 18, 13));
         |                              ^
      10 |         expect(result.end).toBeDate(new Date(2014, 4 - 1, 18, 16));
      11 |     });
      12 | });

      at test/en/en.test.ts:9:30
      at Object.<anonymous> (test/en/en.test.ts:6:5)

  ● Test - Quoted Expressions

    Expected date to be: Fri Apr 18 2014 12:00:00 GMT+0200 (Mitteleuropäische Sommerzeit) Received: Fri Apr 18 2014 13:00:00 GMT+0200 (Mitteleuropäische Sommerzeit) ([ParsingComponents {knownValues: {"year":2014,"month":4,"day":18}, impliedValues: {"hour":12,"minute":0,"second":0,"millisecond":0}}])

      43 |     testSingleCase(chrono, "The date is '2014-04-18'", (result) => {
      44 |         expect(result.text).toContain("2014-04-18");
    > 45 |         expect(result.start).toBeDate(new Date(2014, 4 - 1, 18, 12));
         |                              ^
      46 |     });
      47 | });
      48 |

      at test/en/en.test.ts:45:30
      at Object.<anonymous> (test/en/en.test.ts:43:5)

  ● Test - Random text

    Expected date to be: Mon May 20 2013 09:00:00 GMT+0200 (Mitteleuropäische Sommerzeit) Received: Mon May 20 2013 10:00:00 GMT+0200 (Mitteleuropäische Sommerzeit) ([ParsingComponents {knownValues: {"month":5,"day":20,"year":2013,"weekday":2,"hour":9,"minute":0,"meridiem":0}, impliedValues: {"second":0,"millisecond":0}}])

      87 |         expect(result.text).toBe("9:00 AM to 5:00 PM, Tuesday, 20 May 2013");
      88 |
    > 89 |         expect(result.start).toBeDate(new Date(2013, 4, 20, 9, 0));
         |                              ^
      90 |         expect(result.end).toBeDate(new Date(2013, 4, 20, 17, 0));
      91 |     });
      92 |

      at test/en/en.test.ts:89:30
      at Object.<anonymous> (test/en/en.test.ts:86:5)

  console.log
    ISOFormatParser extracted result [ParsingResult {index: 20, text: '2014-04-18', ...}]

      at src/chrono.ts:127:41
          at Array.map (<anonymous>)

  console.log
    ENTimeExpressionParser extracted result [ParsingResult {index: 28, text: '18', ...}]

      at src/chrono.ts:127:41
          at Array.map (<anonymous>)

  console.log
    ENTimeExpressionParser extracted result [ParsingResult {index: 31, text: '13:00 - 16:00', ...}]

      at src/chrono.ts:127:41
          at Array.map (<anonymous>)

  console.log
    ENMergeDateTimeRefiner merged [ParsingResult {index: 20, text: '2014-04-18', ...}] and [ParsingResult {index: 31, text: '13:00 - 16:00', ...}] into [ParsingResult {index: 20, text: '2014-04-18 13:00 - 16:00', ...}]

      at src/common/abstractRefiners.ts:54:29
          at Array.map (<anonymous>)

  console.log
    ISOFormatParser extracted result [ParsingResult {index: 13, text: '2014-04-18', ...}]

      at src/chrono.ts:127:41
          at Array.map (<anonymous>)

  console.log
    ENTimeExpressionParser extracted result [ParsingResult {index: 21, text: '18', ...}]

      at src/chrono.ts:127:41
          at Array.map (<anonymous>)

  console.log
    ENMonthNameParser extracted result [ParsingResult {index: 32, text: 'May 2013', ...}]

      at src/chrono.ts:127:41
          at Array.map (<anonymous>)

  console.log
    ENMonthNameLittleEndianParser extracted result [ParsingResult {index: 29, text: '20 May 2013', ...}]

      at src/chrono.ts:127:41
          at Array.map (<anonymous>)

  console.log
    ENWeekdayParser extracted result [ParsingResult {index: 20, text: 'Tuesday,', ...}]

      at src/chrono.ts:127:41
          at Array.map (<anonymous>)

  console.log
    ENTimeExpressionParser extracted result [ParsingResult {index: 0, text: '9:00 AM to 5:00 PM', ...}]

      at src/chrono.ts:127:41
          at Array.map (<anonymous>)

  console.log
    ENTimeExpressionParser extracted result [ParsingResult {index: 29, text: '20', ...}]

      at src/chrono.ts:127:41
          at Array.map (<anonymous>)

  console.log
    ENTimeExpressionParser extracted result [ParsingResult {index: 36, text: '2013', ...}]

      at src/chrono.ts:127:41
          at Array.map (<anonymous>)

  console.log
    MergeWeekdayComponentRefiner merged [ParsingResult {index: 20, text: 'Tuesday,', ...}] and [ParsingResult {index: 29, text: '20 May 2013', ...}] into [ParsingResult {index: 20, text: 'Tuesday, 20 May 2013', ...}]

      at src/common/abstractRefiners.ts:54:29
          at Array.map (<anonymous>)

  console.log
    ENMergeDateTimeRefiner merged [ParsingResult {index: 0, text: '9:00 AM to 5:00 PM', ...}] and [ParsingResult {index: 20, text: 'Tuesday, 20 May 2013', ...}] into [ParsingResult {index: 0, text: '9:00 AM to 5:00 PM, Tuesday, 20 May 2013', ...}]

      at src/common/abstractRefiners.ts:54:29
          at Array.map (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 5 passed, 8 total
Snapshots:   0 total
Time:        1.423 s
Ran all test suites matching /en.test/i.
```

**Comment by wanasit** [comment]
@georgd first, let me merge your change first as it looks safe enough, and investigating the broken tests on your local may take a while.
(I added the tests in 51c363e668d51c254e6e41e3d431c5f3204c21ac if you could double check)

About the one-hour diff, first, let's try to check out the latest master again. I'm thinking the timezone offset calculation may not work correctly. If you want to try debugging on your local, the logic is in `results.ts` around functions `ParsingComponents.date()` and `ParsingComponents.getSystemTimezoneAdjustmentMinute()`.

It would be also nice if you could let me know what is the output of the following code on you local:
```
console.log(new Date())
console.log(new Date().getTimezoneOffset())
```

**Comment by georgd** [comment]
Thanks for merging.

I don’t know if I’m able to debug it. Anyway, here’s the output from my console:

```
> console.log(new Date())
2022-02-21T08:18:21.196Z
undefined
> console.log(newDate().getTimezoneOffset())
Uncaught ReferenceError: newDate is not defined
> console.log(new Date().getTimezoneOffset())
-60
undefined
```

**Comment by georgd** [comment]
@wanasit I’m getting the same result on Windows.

I got some results, but haven’t gotten far enough to identify the root of this issue.

The effect is connected to DST calculation. At some point, a wrong date in the tests interferes with the actual test date. E.g. in https://github.com/wanasit/chrono/blob/51c363e668d51c254e6e41e3d431c5f3204c21ac/test/de/de_weekday.test.ts#L125 the target date is in December, but a new Date object is created first for a date in August. Usually, as the target date has no timezone given, target timezone offset and system timezone offset should cancel each other out. as per `date.getSystemTimezoneAdjustmentMinute()`. Here, however, an offset of -60 is returned by this method, because `currentTimezoneOffset` is calculated as 60 and `targetTimezoneOffset` is 120 – `this.get("timnezoneOffset")` being `null`  and `this.reference.timezoneOffset` being 120.

If you change above line in the test to 

```
    testSingleCase(chrono.de, "Sonntag, den 6. Dezember 2014", new Date(2012, 11, 9), (result) => {
```

the test will pass.

Does this make sense?

**Comment by georgd** [comment]
@wanasit I’m sorry, I don’t fully understand where the issue originates. From what I could test, there should be a DST correction somewhere but I can’t find any reference to DST anywhere. And it’s curious that I seem to be the only one affected by this.

**Comment by wanasit** [comment]
Hello. @georgd I think I may have found and fixed the problem, could you try running the test in the latest master?

The DST is the issue, when the timezone is not specified, chrono should use the DST offset calculate at the target date, not the src/ref date.

**Comment by georgd** [comment]
Hello @wanasit thanks for your work. The master hasn’t changed yet. Once the changes are up, I’ll happily test :)

**Comment by georgd** [comment]
Hello @wanasit thanks again, most tests pass now. Still, I see seven failing. To be sure it isn’t something in my fork, I freshly cloned your repo. Here are the last lines:

```
 FAIL  test/fr/fr_time_units_ago.test.ts
  ● Test - Single Expression (Casual)

    Expected date to be: Sat Mar 10 2012 00:00:00 GMT+0100 (Mitteleuropäische Normalzeit) Received: Fri Mar 09 2012 23:00:00 GMT+0100 (Mitteleuropäische Normalzeit) ([ParsingComponents {knownValues: {"month":3,"year":2012}, impliedValues: {"day":10,"hour":0,"minute":0,"second":0,"millisecond":0,"timezoneOffset":120}}, reference: {"instant":"2012-08-09T22:00:00.000Z"}])

      70 |         expect(result.text).toBe("il y a 5 mois");
      71 |
    > 72 |         expect(result.start).toBeDate(new Date(2012, 3 - 1, 10));
         |                              ^
      73 |     });
      74 |
      75 |     testSingleCase(chrono.fr, "il y a 5 ans, on a fait quelque chose", new Date(2012, 8 - 1, 10, 22, 22), (result) => {

      at checkResult (test/fr/fr_time_units_ago.test.ts:72:30)
      at Object.<anonymous> (test/fr/fr_time_units_ago.test.ts:63:5)


Test Suites: 7 failed, 57 passed, 64 total
Tests:       7 failed, 256 passed, 263 total
Snapshots:   0 total
Time:        40.023 s
Ran all test suites.
```

**Pull request merged**
