### PR TITLE
Fix order of dashed date for spanish

### PR DESCRIPTION
**Pull request by francof**
The dates in spanish when using dashed format usually go dd/mm/yyyy, not mm/dd/yyyy.

This PR fixes the parser and the corresponding tests.

### CODE REVIEW

**Comment by gimenete** [comment]
LGTM. Thanks!

**Comment by penne12** [comment]
@Schultzer I agree - we can't change a test without breaking compatibility, and I don't think this change is worth the tradeoff.

**Comment by francof** [comment]
Sorry guys, was AFK, I will revert soon

**Comment by penne12** [comment]
@francof Don't worry about it. Thanks so much for contributing!

**Pull request closed without merging**
