### PR TITLE
Forward dates only when implying weekday

### PR DESCRIPTION
**Pull request by gregeinfrank**
In response to https://github.com/wanasit/chrono/issues/43 - this is a feature we also needed. Defaulting to the past doesn't work for scheduling, etc So I'm sharing this in hopes that others find it useful.

If you want to find the closest upcoming monday, but the closest monday was in the past the current implementation will choose the monday in the past.

This defaults everything to today or in the future. If you want the past using a weekday, you have to type "last monday", etc

### CODE REVIEW

**Comment by penne12** [comment]
+1 - love this, and it'll defiantly help with my use case.

**Comment by j6k4m8** [comment]
a *huge* +1 from me as well.

**Comment by penne12** [comment]
@gregeinfrank Could you make this configurable, please?

**Comment by gregeinfrank** [comment]
@penne12 I've updated to make `forwardDatesOnly` a config option cc/ @wanasit

**Comment by penne12** [comment]
I've merged it - thanks$

**Comment by sharpshark28** [comment]
Seems like a configurable option that should apply beyond just weekdays, such as "Dec 5" would select Dec 5 2015 because it's closer than Dec 5 2016.

**Pull request merged**
