### PR TITLE
Migration zh-hant from v1

### PR DESCRIPTION
**Pull request by DingWeizhe**
Move ZH-Hant from v1

### CODE REVIEW

**Comment by DingWeizhe** [comment]
I have temporarily released the new package [(chrono-node-v2-zh-preview)](https://www.npmjs.com/package/chrono-node).
If you need to use it first, you can try it.
But when this PR is approved, I will set the package as deprecated.

**Comment by wanasit** [comment]
@DingWeizhe I'm very sorry for my slow reply. 
Thank you for you improvement! I'm really appreciate you help working on this.

**Comment by wanasit** [comment]
Your change looks good to me. The only comment/concern I have is I'm not sure if `zhHant` (e.g. `chrono.zhHant`) is a common way to refer to the locale (e.g. I thought it should be `chrono.zh` and `chrono.zh.hant`)

I'm merging your change, but let me do some research about what is the common pattern for that first before publishing this.

**Comment by wanasit** [comment]
Also. Happy Christmas! btw.

**Pull request merged**
